# config/meta.yml
 meta_product_name: "Coach Leon"
 meta_title: "Coach Leon - Realise tes objectifs"
 meta_description: "Coach Leon - Realise tes objectifs avec un programme nutritionnel et sportif personnalise"
 meta_image: "og.png" # should exist in `app/assets/images/`
